# 汇聚层
类似于GNN中的汇聚层，当我们处理图像的时候，我们希望逐渐降低隐藏表示的空间分辨率、聚集信息，这样随着我们在神经网络中层叠的上升，每个神经元对其敏感的感受野（输入）就越大。

机器学习任务通常会跟全局的问题有关，例如图片中有没有猫呢？最后一层应该对整个输入的全局敏感，通过逐渐聚合信息，生成越来越粗糙的映射，最终实现全局表示的目标。

汇聚层的功能是：降低卷积层对位置的敏感性、降低对空间降采样表示的敏感性。

In [5]:
# max pooling and avg pooling
import torch as t
import torch.nn as nn
from torch import Tensor
def pool2d(X:Tensor,pool_size:tuple,mode="max")->Tensor:
    p_h,p_w = pool_size
    # output definition
    Y = t.zeros((X.shape[0]-p_h+1,X.shape[1]-p_w+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode=="max":
                Y[i,j]=X[i:i+p_h,j:j+p_w].max()
            elif mode == "avg":
                Y[i,j]=X[i:i+p_h,j:j+p_w].mean()
            else:
                raise NotImplementedError("only support avg pooling and max pooling")
    return Y

In [6]:
# max pooling 
X= t.tensor([[0,1,2],[3,4,5],[6,7,8]],dtype=t.float32)
pool2d(X,(2,2))

tensor([[4., 5.],
        [7., 8.]])

In [7]:
# avg pooling
pool2d(X,(2,2),mode="avg")

tensor([[2., 3.],
        [5., 6.]])

# padding and stride 填充和步幅
和卷积层中的很类似

In [8]:
X=t.arange(16,dtype=t.float32).reshape(1,1,4,4,)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [9]:
pooling = nn.MaxPool2d(3)
pooling(X)

tensor([[[[10.]]]])

In [10]:
# 填充和步幅可以手动设定
pooling  = nn.MaxPool2d(3,padding=1,stride=2)
pooling(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

# 处理多通道的数据

In [11]:
X =t.cat((X,X+1),0)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]],


        [[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [12]:
pooling(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]],


        [[[ 6.,  8.],
          [14., 16.]]]])

In [ ]:
# 可以看到、生成了2个通道的数据